### ISSUE TITLE
Cannot add meta data on ingested data

### ISSUE THREAD

**Issue by bertrandrigaud** [onedata/onedata#28]
On rc8, when using Import strategy: Simple scan, one can't add metadata:
"Cannot save metadata: Internal Sever Error"

**Comment by groundnuty** [comment]
@bertrandrigaud at we have no way to check your request against rc8. Most likely it has been resolved as we recently had a demo session in DI4R conference presenting automated metadata ingestion. 
Please try using Onedata 18.02.0-rc12 or at least 18.02.0-rc11.

**Comment by groundnuty** [comment]
I'm investigating it with @Frederic GILLARDO <gillardo@lapp.in2p3.fr>
However, if you have any VM on which it's failing, that I could access, it
would make the debugging process much easier.

**Comment by bertrandrigaud** [comment]
Found!

When data is copied directly into the space folder, data doesn't belong to a onedata user:group
So it cannot be modified.
The ingestion process should chown-yze files, shouldn't it?

**Comment by lopiola** [comment]
@bertrandrigaud sorry for late reply, is the issue still valid?

You are right that the dataset has been imported with ownerships unknown to Onedata and this is why the add metadata operation fails.

> The ingestion process should chown-yze files, shouldn't it?

We do not chown any files, especially because the import procedure is dedicated for legacy datasets, which might be readonly or the existing policies might disallow modifications of owners/permissions etc. Instead, you must use LUMA (Local User MApping) to properly map system users/group from the storage to Onedata users and groups. Then, you will be able to add metadata and perform other operations on the dataset as Onedata user.

https://onedata.org/#/home/documentation/doc/administering_onedata/luma.html
